package com.quyet.superapp.enums;

public enum EmailType {
    BLOOD_REQUEST_CREATED,
    BLOOD_REQUEST_WAITING_DONOR,
    BLOOD_REQUEST_APPROVED,
    BLOOD_REQUEST_REJECTED,
    BLOOD_REQUEST_CONFIRMED,
    BLOOD_REQUEST_EXPIRED,           // ❌ Timeout khi donor không phản hồi
    BLOOD_REQUEST_STATUS_UPDATE,

    INVENTORY_ALERT_FOR_REQUEST,

    URGENT_DONOR_ALERT,
    URGENT_DONOR_RESPONSE,
    URGENT_DONOR_VERIFIED,
    URGENT_DONOR_REJECTED,

    PAYMENT_REQUESTED,
    PAYMENT_CONFIRMATION,

    SYSTEM_ANNOUNCEMENT,              // 📢 Gửi thông báo nội bộ toàn hệ thống

    DONATION_REMINDER,
    REGISTER,
    RESET_PASSWORD,
    SYSTEM,
    VERIFY_EMAIL
    }

