# T\u00EAn \u1EE9ng d\u1EE5ng
spring.application.name=seminar

# C\u1EA5u h\u00ECnh server
server.port=${PORT:8080}
# C\u1EA5u h\u00ECnh UTF-8 to\u00E0n h\u1EC7 th\u1ED1ng (Spring Boot + Servlet + JSON)
server.servlet.encoding.charset=UTF-8
server.servlet.oencoding.enabled=true
server.servlet.encoding.force=true

spring.messages.encoding=UTF-8
spring.web.locale=vi_VN
spring.web.locale-resolver=fixed

# C\u1EA5u h\u00ECnh Database - SQL Server
spring.datasource.url=jdbc:mysql://shortline.proxy.rlwy.net:32490/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=wmkxRnprthGJUpdOKVCPKwxthfhzqwSp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# T\u00EAn b\u1EA3ng/t\u00EAn c\u1ED9t gi\u1EEF nguy\u00EAn \u0111\u1ECBnh d\u1EA1ng trong entity
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Gi\u1EA3m log Hibernate
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR

# Gi\u1EA3m log Spring Security
logging.level.org.springframework.security=ERROR

# Log cho package \u1EE9ng d\u1EE5ng
logging.level.com.quyet.superapp=INFO

# C\u1EA5u h\u00ECnh mail
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=quyet21022004@gmail.com
#spring.mail.password=xyhm akjb fdaz ktny
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.default-encoding=UTF-8
#spring.mail.protocol=smtp
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.connectiontimeout=500
#spring.mail.properties.mail.smtp.timeout=500
#spring.mail.properties.mail.smtp.writetimeout=500
#spring.mail.test-connection=false

# Redis
#spring.data.redis.host=host.docker.internal
#spring.data.redis.port=6379
#spring.data.redis.timeout=60000

# JWT
app.jwt.secret=ThayBangChuoiRiengCuaBanPhaiDaiHon32KiTu123456
app.jwt.expiration-ms=86400000

# T\u1ECDa \u0111\u1ED9 c\u1ED1 \u0111\u1ECBnh b\u1EC7nh vi\u1EC7n
hospital.latitude=10.88225
hospital.longitude=106.78228

# Log chi ti\u1EBFt \u0111\u1EC3 ph\u00E1t hi\u1EC7n mapping tr\u00F9ng
logging.level.org.springframework.web=DEBUG
