-- Nếu để ID tự động tăng:
INSERT INTO City (name_city) VALUES (N'TP Hồ Chí Minh');

INSERT INTO District (district_name, city_id) VALUES (N'Quận 1', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Quận 3', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Quận 4', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Quận 5', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Quận 6', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Quận 7', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Quận 8', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Quận 10', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Quận 11', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Quận 12', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Gò Vấp', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Bình Thạnh', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Phú Nhuận', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Tân Bình', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Tân Phú', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Bình Tân', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Thủ Đức', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Bình Chánh', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Củ Chi', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Hóc Môn', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Nhà Bè', 1);
INSERT INTO District (district_name, city_id) VALUES (N'Cần Giờ', 1);

INSERT INTO Ward (ward_name, district_id) VALUES (N'Bến Nghé', 1);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Bến Thành', 1);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Cầu Kho', 1);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Cầu Ông Lãnh', 1);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Cô Giang', 1);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Đa Kao', 1);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Nguyễn Thái Bình', 1);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phạm Ngũ Lão', 1);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Định', 1);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 1', 2);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 2', 2);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 3', 2);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 4', 2);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 5', 2);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 9', 2);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 10', 2);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 11', 2);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 12', 2);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 13', 2);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 14', 2);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 1', 3);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 2', 3);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 3', 3);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 4', 3);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 6', 3);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 8', 3);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 9', 3);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 10', 3);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 12', 3);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 13', 3);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 14', 3);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 15', 3);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 16', 3);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 18', 3);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 1', 4);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 2', 4);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 3', 4);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 4', 4);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 5', 4);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 6', 4);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 7', 4);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 8', 4);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 9', 4);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 10', 4);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 11', 4);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 12', 4);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 13', 4);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 14', 4);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 15', 4);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 1', 5);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 2', 5);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 3', 5);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 4', 5);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 5', 5);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 6', 5);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 7', 5);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 8', 5);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 9', 5);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 10', 5);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 11', 5);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 12', 5);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 13', 5);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 14', 5);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Phú', 6);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Hưng', 6);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Kiểng', 6);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Quy', 6);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phú Thuận', 6);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Bình Thuận', 6);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Thuận Đông', 6);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Thuận Tây', 6);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phú Mỹ', 6);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 1', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 2', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 3', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 4', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 5', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 6', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 7', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 8', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 9', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 10', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 11', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 12', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 13', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 14', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 15', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 16', 7);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 1', 8);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 2', 8);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 3', 8);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 4', 8);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 5', 8);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 6', 8);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 7', 8);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 8', 8);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 9', 8);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 10', 8);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 11', 8);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 12', 8);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 13', 8);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 14', 8);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 15', 8);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 1', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 2', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 3', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 4', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 5', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 6', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 7', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 8', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 9', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 10', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 11', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 12', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 13', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 14', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 15', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 16', 9);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Chánh Hiệp', 10);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Thạnh Lộc', 10);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Thạnh Xuân', 10);
INSERT INTO Ward (ward_name, district_id) VALUES (N'An Phú Đông', 10);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Thới Hiệp', 10);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Hiệp Thành', 10);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Thới Nhất', 10);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Đông Hưng Thuận', 10);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Trung Mỹ Tây', 10);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Hưng Thuận', 10);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 1', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 3', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 4', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 5', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 6', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 7', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 8', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 9', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 10', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 11', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 12', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 13', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 14', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 15', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 16', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 17', 11);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 1', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 2', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 3', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 5', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 6', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 7', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 11', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 12', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 13', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 14', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 15', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 17', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 19', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 21', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 22', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 24', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 25', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 26', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 27', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 28', 12);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 1', 13);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 2', 13);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 3', 13);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 4', 13);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 5', 13);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 7', 13);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 8', 13);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 9', 13);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 10', 13);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 11', 13);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 13', 13);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 15', 13);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 17', 13);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 1', 14);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 2', 14);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 3', 14);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 4', 14);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 5', 14);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 6', 14);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 7', 14);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 8', 14);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 9', 14);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 10', 14);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 11', 14);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 12', 14);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 13', 14);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 14', 14);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phường 15', 14);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phú Thọ Hòa', 15);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phú Thạnh', 15);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phú Trung', 15);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Quý', 15);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Sơn Nhì', 15);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Thành', 15);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Thới Hòa', 15);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tây Thạnh', 15);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Hòa Thạnh', 15);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Hiệp Tân', 15);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Sơn Kỳ', 15);
INSERT INTO Ward (ward_name, district_id) VALUES (N'An Lạc', 16);
INSERT INTO Ward (ward_name, district_id) VALUES (N'An Lạc A', 16);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Bình Hưng Hòa', 16);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Bình Hưng Hòa A', 16);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Bình Hưng Hòa B', 16);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Bình Trị Đông', 16);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Bình Trị Đông A', 16);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Bình Trị Đông B', 16);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Tạo', 16);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Tạo A', 16);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Bình Chiểu', 17);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Hiệp Bình Chánh', 17);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Hiệp Bình Phước', 17);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Linh Chiểu', 17);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Linh Đông', 17);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Linh Tây', 17);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Linh Trung', 17);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Linh Xuân', 17);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tam Bình', 17);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tam Phú', 17);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Trường Thọ', 17);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Bình Chánh', 18);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Bình Hưng', 18);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Bình Lợi', 18);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Đa Phước', 18);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Hưng Long', 18);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Lê Minh Xuân', 18);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phạm Văn Hai', 18);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phong Phú', 18);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Quy Đức', 18);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Kiên', 18);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Nhựt', 18);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Quý Tây', 18);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Vĩnh Lộc A', 18);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Vĩnh Lộc B', 18);
INSERT INTO Ward (ward_name, district_id) VALUES (N'An Nhơn Tây', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'An Phú', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Bình Mỹ', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Hòa Phú', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Nhuận Đức', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phạm Văn Cội', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phú Hòa Đông', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phú Mỹ Hưng', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phước Hiệp', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phước Thạnh', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phước Vĩnh An', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân An Hội', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Phú Trung', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Thạnh Đông', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Thạnh Tây', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Thông Hội', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Thái Mỹ', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Trung An', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Trung Lập Hạ', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Trung Lập Thượng', 19);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Bà Điểm', 20);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Đông Thạnh', 20);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Nhị Bình', 20);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Hiệp', 20);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Thới Nhì', 20);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tân Xuân', 20);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Thới Tam Thôn', 20);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Trung Chánh', 20);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Xuân Thới Đông', 20);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Xuân Thới Sơn', 20);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Xuân Thới Thượng', 20);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Hiệp Phước', 21);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Long Thới', 21);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Nhơn Đức', 21);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phú Xuân', 21);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phước Kiển', 21);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Phước Lộc', 21);
INSERT INTO Ward (ward_name, district_id) VALUES (N'An Thới Đông', 22);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Bình Khánh', 22);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Cần Thạnh', 22);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Long Hòa', 22);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Lý Nhơn', 22);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Tam Thôn Hiệp', 22);
INSERT INTO Ward (ward_name, district_id) VALUES (N'Thạnh An', 22);

INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bến Nghé', 1);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bến Thành', 2);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Cầu Kho', 3);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Cầu Ông Lãnh', 4);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Cô Giang', 5);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Đa Kao', 6);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Nguyễn Thái Bình', 7);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phạm Ngũ Lão', 8);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Định', 9);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 1', 10);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 2', 11);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 3', 12);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 4', 13);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 5', 14);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 9', 15);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 10', 16);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 11', 17);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 12', 18);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 13', 19);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 14', 20);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 1', 21);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 2', 22);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 3', 23);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 4', 24);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 6', 25);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 8', 26);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 9', 27);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 10', 28);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 12', 29);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 13', 30);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 14', 31);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 15', 32);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 16', 33);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 18', 34);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 1', 35);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 2', 36);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 3', 37);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 4', 38);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 5', 39);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 6', 40);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 7', 41);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 8', 42);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 9', 43);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 10', 44);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 11', 45);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 12', 46);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 13', 47);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 14', 48);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 15', 49);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 1', 50);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 2', 51);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 3', 52);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 4', 53);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 5', 54);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 6', 55);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 7', 56);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 8', 57);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 9', 58);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 10', 59);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 11', 60);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 12', 61);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 13', 62);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 14', 63);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Phú', 64);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Hưng', 65);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Kiểng', 66);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Quy', 67);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phú Thuận', 68);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bình Thuận', 69);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Thuận Đông', 70);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Thuận Tây', 71);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phú Mỹ', 72);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 1', 73);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 2', 74);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 3', 75);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 4', 76);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 5', 77);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 6', 78);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 7', 79);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 8', 80);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 9', 81);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 10', 82);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 11', 83);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 12', 84);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 13', 85);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 14', 86);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 15', 87);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 16', 88);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 1', 89);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 2', 90);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 3', 91);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 4', 92);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 5', 93);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 6', 94);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 7', 95);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 8', 96);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 9', 97);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 10', 98);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 11', 99);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 12', 100);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 13', 101);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 14', 102);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 15', 103);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 1', 104);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 2', 105);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 3', 106);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 4', 107);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 5', 108);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 6', 109);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 7', 110);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 8', 111);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 9', 112);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 10', 113);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 11', 114);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 12', 115);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 13', 116);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 14', 117);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 15', 118);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 16', 119);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Chánh Hiệp', 120);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Thạnh Lộc', 121);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Thạnh Xuân', 122);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường An Phú Đông', 123);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Thới Hiệp', 124);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Hiệp Thành', 125);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Thới Nhất', 126);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Đông Hưng Thuận', 127);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Trung Mỹ Tây', 128);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Hưng Thuận', 129);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 1', 130);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 3', 131);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 4', 132);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 5', 133);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 6', 134);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 7', 135);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 8', 136);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 9', 137);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 10', 138);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 11', 139);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 12', 140);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 13', 141);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 14', 142);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 15', 143);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 16', 144);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 17', 145);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 1', 146);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 2', 147);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 3', 148);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 5', 149);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 6', 150);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 7', 151);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 11', 152);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 12', 153);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 13', 154);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 14', 155);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 15', 156);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 17', 157);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 19', 158);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 21', 159);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 22', 160);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 24', 161);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 25', 162);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 26', 163);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 27', 164);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 28', 165);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 1', 166);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 2', 167);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 3', 168);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 4', 169);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 5', 170);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 7', 171);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 8', 172);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 9', 173);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 10', 174);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 11', 175);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 13', 176);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 15', 177);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 17', 178);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 1', 179);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 2', 180);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 3', 181);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 4', 182);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 5', 183);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 6', 184);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 7', 185);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 8', 186);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 9', 187);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 10', 188);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 11', 189);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 12', 190);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 13', 191);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 14', 192);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phường 15', 193);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phú Thọ Hòa', 194);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phú Thạnh', 195);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phú Trung', 196);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Quý', 197);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Sơn Nhì', 198);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Thành', 199);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Thới Hòa', 200);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tây Thạnh', 201);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Hòa Thạnh', 202);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Hiệp Tân', 203);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Sơn Kỳ', 204);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường An Lạc', 205);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường An Lạc A', 206);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bình Hưng Hòa', 207);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bình Hưng Hòa A', 208);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bình Hưng Hòa B', 209);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bình Trị Đông', 210);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bình Trị Đông A', 211);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bình Trị Đông B', 212);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Tạo', 213);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Tạo A', 214);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bình Chiểu', 215);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Hiệp Bình Chánh', 216);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Hiệp Bình Phước', 217);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Linh Chiểu', 218);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Linh Đông', 219);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Linh Tây', 220);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Linh Trung', 221);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Linh Xuân', 222);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tam Bình', 223);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tam Phú', 224);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Trường Thọ', 225);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bình Chánh', 226);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bình Hưng', 227);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bình Lợi', 228);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Đa Phước', 229);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Hưng Long', 230);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Lê Minh Xuân', 231);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phạm Văn Hai', 232);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phong Phú', 233);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Quy Đức', 234);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Kiên', 235);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Nhựt', 236);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Quý Tây', 237);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Vĩnh Lộc A', 238);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Vĩnh Lộc B', 239);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường An Nhơn Tây', 240);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường An Phú', 241);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bình Mỹ', 242);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Hòa Phú', 243);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Nhuận Đức', 244);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phạm Văn Cội', 245);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phú Hòa Đông', 246);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phú Mỹ Hưng', 247);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phước Hiệp', 248);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phước Thạnh', 249);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phước Vĩnh An', 250);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân An Hội', 251);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Phú Trung', 252);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Thạnh Đông', 253);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Thạnh Tây', 254);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Thông Hội', 255);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Thái Mỹ', 256);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Trung An', 257);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Trung Lập Hạ', 258);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Trung Lập Thượng', 259);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bà Điểm', 260);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Đông Thạnh', 261);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Nhị Bình', 262);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Hiệp', 263);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Thới Nhì', 264);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tân Xuân', 265);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Thới Tam Thôn', 266);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Trung Chánh', 267);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Xuân Thới Đông', 268);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Xuân Thới Sơn', 269);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Xuân Thới Thượng', 270);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Hiệp Phước', 271);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Long Thới', 272);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Nhơn Đức', 273);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phú Xuân', 274);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phước Kiển', 275);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Phước Lộc', 276);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường An Thới Đông', 277);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Bình Khánh', 278);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Cần Thạnh', 279);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Long Hòa', 280);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Lý Nhơn', 281);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Tam Thôn Hiệp', 282);
INSERT INTO Address (name_street, ward_id) VALUES (N'Số 1 Đường Thạnh An', 283);




curl -X POST "http://localhost:6969/api/v1/add" ^
  -H "Content-Type: application/json" ^
  -d "{\"id\":\"JCNT\",\"name\":\"Cafe Java khuya đậm cùng Ngọc Trinh\",\"price\":29000}"